name: 'Hello World Action'
description: 'Send a hello world in a runner'
inputs:
  name:
    description: 'La personne a dit bonjour'
    required: true
    default: 'Pauline'
outputs:
  response:
    description: 'Réponse de l'action"
runs:
  using: 'node16'
  main: 'index.js'